### ISSUE TITLE
Menu doesn't show up

### ISSUE THREAD

**Issue by flustix** [DarkFlare69/MK7-Online-NTR-Plugin-v3#3]
When i press select nothing happens (I have enabled the Plugin Loader)

**Comment by DarkFlare69** [comment]
> When i press select nothing happens (I have enabled the Plugin Loader)

Do you have the plugin in the right folder for your region?

USA   SD:/luma/plugins/0004000000030800
EUR    SD:/luma/plugins/0004000000030700
JPN    SD:/luma/plugins/0004000000030600

**Comment by flustix** [comment]
yes i did
