### ISSUE TITLE
Luma says the Plugin is outdated-ed please fix! 

### ISSUE THREAD

**Issue by vater1203** [DarkFlare69/MK7-Online-NTR-Plugin-v3#4]

**Comment by DarkFlare69** [comment]
This is not an issue with my plugin. This error occurs whenever you run CTGP-7. It will discreetly change the boot.firm to one that is incompatible with almost every currently released plugin.  Redownload the boot.firm from here: https://github.com/Nanquitas/Luma3DS/releases
